version: "3"

services:
  gateway-service:
    image: paxapp/pax-gateway:latest
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3002:3002
      - 9229:9229
    command: npm start
